# Generated by Django 4.2.2 on 2023-06-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('skill_level', models.CharField(choices=[('BE', 'Beginner'), ('AB', 'Advanced Beginner'), ('IN', 'Intermediate'), ('AD', 'Advanced'), ('EX', 'EXPERT')], default='BE', max_length=2)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('last_updated', models.DateTimeField(verbose_name='last updated')),
            ],
        ),
    ]
