# Generated by Django 4.2.2 on 2023-06-17 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_skill_last_updated_alter_skill_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 17, 13, 37, 44, 956038, tzinfo=datetime.timezone.utc), verbose_name='last updated'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 17, 13, 37, 44, 956038, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
