# Generated by Django 4.2.2 on 2023-06-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_skill_last_updated_alter_skill_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=200)),
                ('certificate_origin', models.CharField(max_length=200)),
                ('certificate_issued', models.DateField(verbose_name='Date issued')),
            ],
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Advanced Beginner', 'Advanced Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'EXPERT')], default='Beginner', max_length=20),
        ),
    ]
